### ISSUE TITLE
.us.com TLD doesnt work

### ISSUE THREAD

**Issue by cryptiklemur** [AkenRoberts/ParseUrl#1]

**Comment by AkenRoberts** [comment]
Thanks for mentioning that! I've had "Update ParseUrl" on my to-do list for a while now, with intentions to make it Composer savvy, and verify some of the new domains that are propping up.

You're right, though. Lots of domains would fail currently, including anything that's two letters (`.io`, `.us`), or 2.3 letters (`.us.com`).

Can't promise exactly when I'll fix this up, but I appreciate the issue submission. :)

**Comment by cryptiklemur** [comment]
Changing the regex to `'/(\.(?:[a-z]{3}|[a-z]{2}(?:\.[a-z]{2})?|[a-z]{2}(?:\.[a-z]{3})?))$/'` should work. Might be able to make it cleaner tho

**Comment by cryptiklemur** [comment]
`'/(\.(?:[a-z]{3}|[a-z]{2}(?:\.[a-z]{2,3})?))$/'` actually is shorter. I dont know about the `io`, and `us` though, could also just change the first three to a `2,3`

`'/(\.(?:[a-z]{2,3}|[a-z]{2}(?:\.[a-z]{2,3})?))$/'`

**Comment by AkenRoberts** [comment]
Right, that's what I was about to write; I'd probably just change the length restrictions to accept different lengths. I don't think it's worth being extremely specific about each scenario, since the goal is just to parse the different parts of the URL, not necessarily to enforce their legitimacy.

**Comment by cryptiklemur** [comment]
Sweet
